### PR TITLE
WIP: Add instructions for compiling from source

### PR DESCRIPTION
**Pull request by oxr463**
Linux sources are cloned to `/usr/src/linux`. Trying to figure out the proper way to integrate this driver repository.

### CODE REVIEW

**Comment by ohquait** [comment]
@loimu 
how can write or send a patch ?
at master on Mar 19. 2022 i can build from source with a few patches in header-files:
please ignore the first piece of patch, that is just for cut the driver out of kernel-tree for testings
and just targeted to the Makefile, this was not the problem by finding headers on compiling,
after few test-builds i have moved the headers from your /include to the main-dir of rtbth-dkms
and with the corrections from patch below all builds absolute good: 
[https://www.qua-it.org/XFCE/shots/share-with-pclos/pclos/rtbth-3.9.7-makefile+headers.patch](url)

**Comment by aadeshsonawane** [comment]
@loimu any plans about upstreaming this driver? FWIW, there's a related open issue on kernel bugzilla https://bugzilla.kernel.org/show_bug.cgi?id=84521

Is there anything where we can help?

Thanks!

**Comment by loimu** [comment]
@aadeshsonawane It is not possible. The driver itself is proprietary with the exception of the wrapper kernel module part. Technically you need a new driver either written from scratch or reverse-engineered in order to accomplish what you want, which appears to be unrealistic. The only possible shortcut is to convince Mediatek to open the driver, but I'm not sure if they even have the source at this day and age.

**Comment by chiddekel** [comment]
Hey - what about start similar project (NDISwrapper)  for windows bluetooth driver under linux like:
[NDISwrapper](https://en.wikipedia.org/wiki/NDISwrapper)

**Pull request closed without merging**
